ERROR - 2023-06-30 00:38:40 --> Error connecting to the database: mysqli_sql_exception: No se puede establecer una conexión ya que el equipo de destino denegó expresamente dicha conexión.
 in C:\xampp_74\htdocs\ci4\system\Database\MySQLi\Connection.php:174
Stack trace:
#0 C:\xampp_74\htdocs\ci4\system\Database\MySQLi\Connection.php(174): mysqli->real_connect('localhost', '', '', '', 3306, '', 0)
#1 C:\xampp_74\htdocs\ci4\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp_74\htdocs\ci4\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp_74\htdocs\ci4\app\Controllers\Home.php(49): CodeIgniter\Database\BaseConnection->query('SELECT idperson...')
#4 C:\xampp_74\htdocs\ci4\system\CodeIgniter.php(934): App\Controllers\Home->testbd()
#5 C:\xampp_74\htdocs\ci4\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#6 C:\xampp_74\htdocs\ci4\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\xampp_74\htdocs\ci4\index.php(67): CodeIgniter\CodeIgniter->run()
#8 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: No se puede establecer una conexión ya que el equipo de destino denegó expresamente dicha conexión.
 in C:\xampp_74\htdocs\ci4\system\Database\MySQLi\Connection.php:218
Stack trace:
#0 C:\xampp_74\htdocs\ci4\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp_74\htdocs\ci4\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp_74\htdocs\ci4\app\Controllers\Home.php(49): CodeIgniter\Database\BaseConnection->query('SELECT idperson...')
#3 C:\xampp_74\htdocs\ci4\system\CodeIgniter.php(934): App\Controllers\Home->testbd()
#4 C:\xampp_74\htdocs\ci4\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#5 C:\xampp_74\htdocs\ci4\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xampp_74\htdocs\ci4\index.php(67): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2023-06-30 00:38:40 --> Unable to connect to the database.
Main connection [MySQLi]: No se puede establecer una conexión ya que el equipo de destino denegó expresamente dicha conexión.

in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
 2 APPPATH\Controllers\Home.php(49): CodeIgniter\Database\BaseConnection->query('SELECT idpersonal, cedula, apellido1, apellido2, nombres, genero FROM esq_datos_personales.personal limit 100  ')
 3 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Home->testbd()
 4 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 5 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 6 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2023-06-30 00:39:37 --> Error connecting to the database: ErrorException: pg_connect(): Unable to connect to PostgreSQL server: invalid connection option &quot;username&quot; in C:\xampp_74\htdocs\ci4\system\Database\Postgre\Connection.php:75
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_connect(): U...', 'C:\\xampp_74\\htd...', 75, Array)
#1 C:\xampp_74\htdocs\ci4\system\Database\Postgre\Connection.php(75): pg_connect('host=192.168.2....')
#2 C:\xampp_74\htdocs\ci4\system\Database\BaseConnection.php(391): CodeIgniter\Database\Postgre\Connection->connect(false)
#3 C:\xampp_74\htdocs\ci4\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#4 C:\xampp_74\htdocs\ci4\app\Controllers\Home.php(49): CodeIgniter\Database\BaseConnection->query('SELECT idperson...')
#5 C:\xampp_74\htdocs\ci4\system\CodeIgniter.php(934): App\Controllers\Home->testbd()
#6 C:\xampp_74\htdocs\ci4\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#7 C:\xampp_74\htdocs\ci4\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp_74\htdocs\ci4\index.php(67): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2023-06-30 00:39:37 --> Unable to connect to the database.
Main connection [Postgre]: pg_connect(): Unable to connect to PostgreSQL server: invalid connection option &quot;username&quot;
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
 2 APPPATH\Controllers\Home.php(49): CodeIgniter\Database\BaseConnection->query('SELECT idpersonal, cedula, apellido1, apellido2, nombres, genero FROM esq_datos_personales.personal limit 100  ')
 3 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Home->testbd()
 4 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 5 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 6 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2023-06-30 00:39:38 --> Error connecting to the database: ErrorException: pg_connect(): Unable to connect to PostgreSQL server: invalid connection option &quot;username&quot; in C:\xampp_74\htdocs\ci4\system\Database\Postgre\Connection.php:75
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_connect(): U...', 'C:\\xampp_74\\htd...', 75, Array)
#1 C:\xampp_74\htdocs\ci4\system\Database\Postgre\Connection.php(75): pg_connect('host=192.168.2....')
#2 C:\xampp_74\htdocs\ci4\system\Database\BaseConnection.php(391): CodeIgniter\Database\Postgre\Connection->connect(false)
#3 C:\xampp_74\htdocs\ci4\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#4 C:\xampp_74\htdocs\ci4\app\Controllers\Home.php(49): CodeIgniter\Database\BaseConnection->query('SELECT idperson...')
#5 C:\xampp_74\htdocs\ci4\system\CodeIgniter.php(934): App\Controllers\Home->testbd()
#6 C:\xampp_74\htdocs\ci4\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#7 C:\xampp_74\htdocs\ci4\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp_74\htdocs\ci4\index.php(67): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2023-06-30 00:39:38 --> Unable to connect to the database.
Main connection [Postgre]: pg_connect(): Unable to connect to PostgreSQL server: invalid connection option &quot;username&quot;
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
 2 APPPATH\Controllers\Home.php(49): CodeIgniter\Database\BaseConnection->query('SELECT idpersonal, cedula, apellido1, apellido2, nombres, genero FROM esq_datos_personales.personal limit 100  ')
 3 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Home->testbd()
 4 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 5 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 6 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-06-30 00:40:07 --> Argument 1 passed to CodeIgniter\Database\BaseResult::getResult() must be of the type string, object given, called in C:\xampp_74\htdocs\ci4\app\Controllers\Home.php on line 50
in SYSTEMPATH\Database\BaseResult.php on line 104.
 1 APPPATH\Controllers\Home.php(50): CodeIgniter\Database\BaseResult->getResult(Object(CodeIgniter\Database\Postgre\Result))
 2 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Home->testbd()
 3 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 4 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
